<?php include("header.phtml") ?>
<?php include("navbar.phtml") ?>
<div class="content">
<div class="page-title">Build a Recipe</div>

<div class="page-edit-body">
    <form class="page-edit-form" action="?page=recipe&action=create">

    <label for="recipe-name">Recipe Title</label>
    <input type="text" name="recipe-name" class="create-field" id="recipe-name-field" />
        <?= isset($RENDER_VARS["old-recipe-name"]) ? $RENDER_VARS["old-recipe-name"] : "" ?>
    </input>

    <label for="recipe-description">Description</label>
    <input type="text" name="recipe-description" class="create-field" id="recipe-description-field" />
        <?= isset($RENDER_VARS["old-recipe-description"]) ? $RENDER_VARS["old-recipe-description"] : "" ?>
    </input>

    <label for="recipe-ingredients">Ingredients</label>
    <input type="text" name="recipe-ingredients" class="create-field" id="recipe-ingredients-field" />
        <?= isset($RENDER_VARS["old-recipe-ingredients"]) ? $RENDER_VARS["old-recipe-ingredients"] : "" ?>
    </input>

    <label for="recipe-instructions">Instructions</label>
    <input type="text" name="recipe-instructions" class="create-field" id="recipe-instructions-field" />
        <?= isset($RENDER_VARS["old-recipe-instructions"]) ? $RENDER_VARS["old-recipe-instructions"] : "" ?>
    </input>

    <button type="submit" class="recipe-button primary-button">Submit</button>



    </form>
</div>


</div>
<?php include("footer.phtml") ?>