<?php include("header.phtml") ?>
<?php include("navbar.phtml") ?>
<div class="content">
<div class="recipe-title"><?= isset($RENDER_VARS["recipe_name"]) ? $RENDER_VARS["recipe_name"] : ""; ?></div>
<div class="recipe-description"><?= isset($RENDER_VARS["description"]) ? $RENDER_VARS["description"] : ""; ?></div>
<div class="recipe-ingredients"><?= isset($RENDER_VARS["ingredients"]) ? $RENDER_VARS["ingredients"] : ""; ?></div>
<div class="recipe-instructions"><?= isset($RENDER_VARS["instructions"]) ? $RENDER_VARS["instructions"] : ""; ?></div>

</div>
<?php include("footer.phtml") ?>