<?php

if(isset($RENDER_VARS["recipes"])) {
    foreach ($RENDER_VARS["recipes"] as $recipe) {
?>

<a href="?page=recipe&id=<?=$recipe['id']?>" class="recipe-tile-link">
    <div class="recipe-tile">
        <div class="recipe-tile-title"><?= isset($recipe["recipe_name"]) ? $recipe["recipe_name"]: ""; ?></div>
        <div class="recipe-tile-description"><?= isset($recipe["description"]) ? $recipe["description"] : ""; ?></div>
     </div>
</a>


<?php
    }
}
?>