<?php include("header.phtml") ?>
<?php include("navbar.phtml") ?>

<div class="login-outer-wrapper">
<div class="login-container">

    <div class="login-header">
        <div class="login-title">Register</div>
    </div>

    <div class="login-body">
        <form class="login-form" id="login-form" method="POST" action="index.php?page=register">
            
            <div id="login-error"><?= isset($RENDER_VARS["err_msg"]) ? $RENDER_VARS["err_msg"] : ""; ?></div>
            <?php require("forms/csrf.phtml") ?>
            <?php require("forms/create.phtml") ?>

            <div class="login-form-section">
                <label for="username">Username</label>
                <input 
                    type="text" 
                    name="username" 
                    class="login-field"     
                    id="username-field" 
                    autofocus
                    value="<?= isset($RENDER_VARS["old_username"]) ? $RENDER_VARS["old_username"] : ""; ?>" 
                >
            </div>

            <div class="login-form-section">                
                <label for="username">Email</label>
                <input 
                    type="email" 
                    name="email" 
                    class="login-field" 
                    id="email-field" 
                    value="<?= isset($RENDER_VARS["old_email"]) ? $RENDER_VARS["old_email"] : ""; ?>" 
                >
            </div>

            <div class="login-form-section">
                <label for="password">Password</label>
                <input 
                    type="password" 
                    name="password" 
                    class="login-field"
                    id="password-field" 
                    value="<?= isset($RENDER_VARS["old_password"]) ? $RENDER_VARS["old_password"] : ""; ?>"
                >
            </div>

            <div class="login-form-section">
                <label for="password2">Verify Password</label>
                <input 
                    type="password" 
                    name="password2" 
                    class="login-field"
                    id="password2-field" 
                    value="<?= isset($RENDER_VARS["old_password"]) ? $RENDER_VARS["old_password"] : ""; ?>"
                >
            </div>

            <div class="login-register-button-group">
                <div class="main-button-group">
                    <button class="login-form-main-button" id="register-button" type="submit">Register</button>
                </div>
                <div class="alt-button-group">
                    <button class="login-form-button" id="login-button">Login</button>
                </div>
            </div>
        </form>
    </div>

</div>
</div>

<?php include("footer.phtml") ?>