<?php include("core/header.phtml") ?>
<?php include("navbar/navbar.phtml") ?>
<div class="content">

<div>Username: <?= isset($RENDER_VARS["username"]) ? $RENDER_VARS["username"] : "" ?></div>
<div>Email: <?= isset($RENDER_VARS["email"]) ? $RENDER_VARS["email"] : "" ?></div>

<?php include("my-recipes.phtml") ?>

<?php include("user-edit-menu.phtml") ?>

</div>
<?php include("core/footer.phtml") ?>