<div class="footer-info-container">

    <div class="footer-author-section">
        <a class="footer-github" target="_blank" href="https://github.com/mwaboff/boff-bakery-recipes">
            Check out the code on Github
        </a>
        ·
        <div class="footer-author">
            Written for Wilmington University DSN6060
        </div>
        ·
        <div class="footer-copyright">© 2020 Michael Aboff</div>

    </div>


</div>