<div class="footer-info-container">

    <div class="footer-author-section">
        <a class="footer-link" target="_blank" href="https://github.com/mwaboff/boff-bakery-recipes">
            View the code on Github
        </a>
        ·
        <div class="footer-note">Written in pure PHP, Javascript, and CSS with love</div>
        ·
        <div class="footer-copyright">© 2020 Michael Aboff</div>

    </div>


</div>